/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LENOVO
 */

import java.awt.AlphaComposite;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.time.LocalDate;
import java.time.Month;
import java.time.temporal.ChronoUnit;
import java.time.format.TextStyle;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSpinner;

public class FrmPerhitunganHari extends javax.swing.JFrame {

    /**
     * Creates new form FrmPerhitunganHari
     */
    public FrmPerhitunganHari() {
        initComponents();
        setTitle("Aplikasi Perhitungan Hari");
        setLocationRelativeTo(null);
        
        // Atur nilai awal spinner tahun
        spnTahun.setModel(new javax.swing.SpinnerNumberModel(2025, 1, 9999, 1));
        
        // Hapus format titik ribuan
        JSpinner.NumberEditor editor = new JSpinner.NumberEditor(spnTahun, "#");
        spnTahun.setEditor(editor);
    }
    
    public class BackgroundPanel extends JPanel {
        private final Image image;

        public BackgroundPanel() {
            ImageIcon icon = new ImageIcon(getClass().getResource("/images/background.JPG"));
            image = icon.getImage();
            setOpaque(true);
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            ImageIcon icon = new ImageIcon(getClass().getResource("/images/background.JPG"));
            Image image = icon.getImage();

            // Ubah Graphics biasa ke Graphics2D
            Graphics2D g2d = (Graphics2D) g.create();

            // Atur level transparansi (0.0f = transparan penuh, 1.0f = solid)
            float opacity = 0.5f; // Ubah nilainya sesuai keinginanmu

            g2d.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER, opacity));
            g2d.drawImage(image, 0, 0, getWidth(), getHeight(), this);

            g2d.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new BackgroundPanel();
        lblJudul = new javax.swing.JLabel();
        lblBulan = new javax.swing.JLabel();
        lblTahun = new javax.swing.JLabel();
        cmbBulan = new javax.swing.JComboBox<>();
        lblKalender = new javax.swing.JLabel();
        Kalender = new com.toedter.calendar.JCalendar();
        btnHitung = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        spnTahun = new javax.swing.JSpinner();
        lblJumlah = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lblInfo = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInfo = new javax.swing.JTextArea();
        lblSelisih = new javax.swing.JLabel();
        lblSeliKal1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        SeliKal1 = new com.toedter.calendar.JCalendar();
        lblSeliKal2 = new javax.swing.JLabel();
        SeliKal2 = new com.toedter.calendar.JCalendar();
        btnSelisih = new javax.swing.JButton();
        lblHasil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Perhitungan Hari");

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblJudul.setText("Aplikasi Perhitungan Hari");

        lblBulan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBulan.setText("Bulan :");

        lblTahun.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTahun.setText("Tahun :");

        cmbBulan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));

        lblKalender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKalender.setText("Atau Pilih dari Kalender :");

        Kalender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Kalender.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                KalenderPropertyChange(evt);
            }
        });

        btnHitung.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnHitung.setText("Hitung Hari");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnHapus.setText("Keluar");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        spnTahun.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        spnTahun.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnTahunStateChanged(evt);
            }
        });

        lblJumlah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJumlah.setText("Jumlah Hari :");

        lblInfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblInfo.setText("Informasi Tambahan :");

        txtInfo.setColumns(20);
        txtInfo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtInfo.setRows(5);
        jScrollPane1.setViewportView(txtInfo);

        lblSelisih.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSelisih.setText("Selisih antara dua tanggal :");

        lblSeliKal1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSeliKal1.setText("Kalender 1 :");

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        SeliKal1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblSeliKal2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSeliKal2.setText("Kalender 2 :");

        SeliKal2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnSelisih.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSelisih.setText("Hitung Selisih");
        btnSelisih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelisihActionPerformed(evt);
            }
        });

        lblHasil.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHasil.setText("-");

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSelisih))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MainPanelLayout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addComponent(lblInfo))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MainPanelLayout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addComponent(lblJumlah)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblHasil))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MainPanelLayout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MainPanelLayout.createSequentialGroup()
                                                    .addComponent(btnHitung)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(btnClear)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnHapus))
                                                .addGroup(MainPanelLayout.createSequentialGroup()
                                                    .addComponent(lblBulan)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(cmbBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(lblTahun)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(spnTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(Kalender, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblKalender, javax.swing.GroupLayout.Alignment.LEADING)))))
                                .addGap(0, 45, Short.MAX_VALUE))
                            .addComponent(jSeparator3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSeliKal1)
                            .addComponent(lblSelisih)
                            .addComponent(SeliKal1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSeliKal2)
                            .addComponent(SeliKal2, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(72, 72, 72))
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(461, 461, 461)
                .addComponent(lblJudul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBulan)
                            .addComponent(lblTahun)
                            .addComponent(cmbBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSelisih))
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(lblKalender))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSeliKal1)))
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Kalender, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnHitung)
                                    .addComponent(btnClear)
                                    .addComponent(btnHapus))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblJumlah)
                                    .addComponent(lblHasil))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblInfo)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(24, Short.MAX_VALUE))
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(SeliKal2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblSeliKal2)
                                .addGap(18, 18, 18)
                                .addComponent(SeliKal1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSelisih)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        try {
            int tahun = (int) spnTahun.getValue();
            String namaBulan = (String) cmbBulan.getSelectedItem();
        
            // Konversi manual nama bulan Indonesia ke Month
            Month bulan = switch (namaBulan.toLowerCase()) {
                case "januari" -> Month.JANUARY;
                case "februari" -> Month.FEBRUARY;
                case "maret" -> Month.MARCH;
                case "april" -> Month.APRIL;
                case "mei" -> Month.MAY;
                case "juni" -> Month.JUNE;
                case "juli" -> Month.JULY;
                case "agustus" -> Month.AUGUST;
                case "september" -> Month.SEPTEMBER;
                case "oktober" -> Month.OCTOBER;
                case "november" -> Month.NOVEMBER;
                case "desember" -> Month.DECEMBER;
                default -> throw new IllegalArgumentException("Bulan tidak valid!");
            };

            LocalDate tanggalAwal = LocalDate.of(tahun, bulan, 1);
            int jumlahHari = tanggalAwal.lengthOfMonth();
            LocalDate tanggalAkhir = tanggalAwal.withDayOfMonth(jumlahHari);

            lblHasil.setText(String.valueOf(jumlahHari));

            txtInfo.setText(
                "Bulan: " + namaBulan + "\n" +
                "Tahun: " + tahun + "\n" +
                "Hari pertama: " + tanggalAwal.getDayOfWeek()
                    .getDisplayName(TextStyle.FULL, new Locale("id")) + "\n" +
                "Hari terakhir: " + tanggalAkhir.getDayOfWeek()
                    .getDisplayName(TextStyle.FULL, new Locale("id"))
            );
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Terjadi kesalahan input!\nPastikan tahun dan bulan diisi dengan benar.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        cmbBulan.setSelectedIndex(0);
        spnTahun.setValue(2025);
        lblHasil.setText("");
        txtInfo.setText("");
        
        Kalender.setDate(new java.util.Date());
        SeliKal1.setDate(new java.util.Date());
        SeliKal2.setDate(new java.util.Date());

        cmbBulan.requestFocus();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int konfirmasi = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin keluar?", "Konfirmasi",
                JOptionPane.YES_NO_OPTION);
        if (konfirmasi == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnSelisihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelisihActionPerformed
        try {
            java.util.Date tgl1 = SeliKal1.getDate();
            java.util.Date tgl2 = SeliKal2.getDate();

            if (tgl1 == null || tgl2 == null) {
                JOptionPane.showMessageDialog(this,
                    "Silakan pilih dua tanggal terlebih dahulu!",
                    "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }

            LocalDate date1 = new java.sql.Date(tgl1.getTime()).toLocalDate();
            LocalDate date2 = new java.sql.Date(tgl2.getTime()).toLocalDate();

            long selisih = Math.abs(ChronoUnit.DAYS.between(date1, date2));

            lblHasil.setText(String.valueOf(selisih));

            txtInfo.setText(
                "Tanggal 1: " + date1 + "\n" +
                "Tanggal 2: " + date2 + "\n" +
                "Selisih antara kedua tanggal adalah " + selisih + " hari."
            );
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Terjadi kesalahan menghitung selisih tanggal.",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSelisihActionPerformed

    private void KalenderPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_KalenderPropertyChange
        if ("calendar".equals(evt.getPropertyName())) {
            java.util.Calendar cal = (java.util.Calendar) evt.getNewValue();
            if (cal != null) {
                int bulan = cal.get(java.util.Calendar.MONTH);
                int tahun = cal.get(java.util.Calendar.YEAR);
                cmbBulan.setSelectedIndex(bulan);
                spnTahun.setValue(tahun);
            }
        }
    }//GEN-LAST:event_KalenderPropertyChange

    private void spnTahunStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnTahunStateChanged
        lblHasil.setText("");
        txtInfo.setText("");
    }//GEN-LAST:event_spnTahunStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPerhitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPerhitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPerhitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPerhitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPerhitunganHari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar Kalender;
    private javax.swing.JPanel MainPanel;
    private com.toedter.calendar.JCalendar SeliKal1;
    private com.toedter.calendar.JCalendar SeliKal2;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnSelisih;
    private javax.swing.JComboBox<String> cmbBulan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblBulan;
    private javax.swing.JLabel lblHasil;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJumlah;
    private javax.swing.JLabel lblKalender;
    private javax.swing.JLabel lblSeliKal1;
    private javax.swing.JLabel lblSeliKal2;
    private javax.swing.JLabel lblSelisih;
    private javax.swing.JLabel lblTahun;
    private javax.swing.JSpinner spnTahun;
    private javax.swing.JTextArea txtInfo;
    // End of variables declaration//GEN-END:variables
}
